### ISSUE TITLE
When I switch to the mobile phone, it is stuck so that I can't slide

### ISSUE THREAD

**Issue by smartsimba** [maxim-saplin/data_table_2#100]
When I switch to the mobile phone, it is stuck so that I can't slide. Could you please check the reason when you have time? Thank you

**Comment by maxim-saplin** [comment]
Please provide more info - reproduction steps, video with the issue, flutter doctor output, code snippets showing how you create widgets from the package etc.

**Comment by smartsimba** [comment]
Hello, in "DataTable2 Fixed Rows/Cols" page, slide left and right, slide up and down, still seriously stuck, I use the version "^2.3.2", thank you
![20220622170003](https://user-images.githubusercontent.com/11230335/174989450-62d347fc-b1e5-496c-94b8-5dc08b39bd16.png)

**Comment by maxim-saplin** [comment]
Now I see it.. Thanks, will investigate for a fix

**Comment by maxim-saplin** [comment]
The problem is reproducible in desktop browser in Chrome dev tools under mobile device emulation mode when touching down and swiping doesn't scroll the table, trackpad scrolling is OK. Tried reproducing the issue in Firefox and Samsung mobile browsers on Android smartphone, on mobile Safari in iPhone simulator - touch scrolling is OK. Since the issue is only related to desktop emulation in DevTools and there's still the capability with Touch Bar I see no reason investing time and fixing that corner case.

https://user-images.githubusercontent.com/7947027/175034329-31fbdd8a-8f04-42b2-87ab-fcca1cb4eab3.mp4
