### ISSUE TITLE
Change Pagination, Next, Prev, Last Page Language?

### ISSUE THREAD

**Issue by DiegoVega19** [maxim-saplin/data_table_2#122]
How can  I change the language for those pagination buttons?
thanks!
![image](https://user-images.githubusercontent.com/45367804/180575480-4cad5a82-1391-4637-8418-0a1f4b1454fe.png)

**Comment by maxim-saplin** [comment]
Hey there, sorry, missed the issue...

You can use Flutter's standard approach to localisation since the widget rely on standard localisation bindings: https://docs.flutter.dev/development/accessibility-and-localization/internationalization

Essentially you have to add flutter_localizations package reference to pub spec yaml and than in main.dart/MaterialApp set the 3 localisation related properties:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/7947027/182085814-37344d76-2a03-4767-a6d2-28ad446c6a80.png">

JIC, you can clone ,master and play with locale in /examples

**Comment by DiegoVega19** [comment]
Hey, Thank you, it works!

**Comment by Priyantha-Kingslake** [comment]
I have a requirement where the localization is set to 'es' but I need the general widgets (i.e. calendars, tables, etc) to have english. Would really appreciate if its allowed to set the locale for the widgets without tight coupling with localization
