### ISSUE TITLE
Divider Color

### ISSUE THREAD

**Issue by Prosa** [maxim-saplin/data_table_2#138]
It is helpful to have a property in DataTable2 class for the divider's color.

**Comment by maxim-saplin** [comment]
The color of the divider is determined via theme value:

```
    final Color? effectiveColor = color
        ?? (context != null ? (DividerTheme.of(context).color ?? Theme.of(context).dividerColor) : null);
```

It is a good practice to use themes rather than have explicit values in properties. You can either change the colour globally in the app theme OR you can override it in single widget the using the `Theme()` widget:

```
              child: Theme(
                  data: ThemeData(dividerColor: Colors.amber),
                  child: DataTable2(
                      dividerThickness: 4,
```

<img width="734" alt="image" src="https://user-images.githubusercontent.com/7947027/191043610-80311e8d-a14e-40ce-857a-f5308c01c670.png">

**Comment by Prosa** [comment]
Yes, I agree with you, it is better to use themes ,but, in this example, if you want to use a different a divider color, it is preferable to have an extra property. It will not be required, but, many times we may want to use a different divider color(to show an error, a warning, etc...). I think that a single property, is better than an extra widget in the widget tree. Just think of it. In my case, the general divider color in theme solves my problem.

**Comment by maxim-saplin** [comment]
Following that approach the widget must have hundreds of JIC shortcut properties should anyone want different text color, size etc.
