### ISSUE TITLE
dataTable 2 inside ListView

### ISSUE THREAD

**Issue by YouSour** [maxim-saplin/data_table_2#145]
hi, how can i use DataTable 2 inside ListView ? thank in advance
example : my widget tree i'm doing 
```
-ListView
  -widget1
  -Expanded(DataTable2)
```

**Comment by maxim-saplin** [comment]
Try putting it inside sized/constrained box and limit vertical dimensions

**Comment by YouSour** [comment]
@maxim-saplin example code pls

**Comment by YouSour** [comment]
@maxim-saplin  i test with DataTable widget flutter it works fine , don't know why dataTable 2 not work :(

**Comment by maxim-saplin** [comment]
I don't get what kind of example code do you expect if my suggestion is wrapping data table in a single widget, e.g. https://api.flutter.dev/flutter/widgets/SizedBox-class.html and setting it's height.

**Comment by maxim-saplin** [comment]
Besides there's a warning/important message that tells NOT TO DO what you actually did by putting the widget into an unbounded parent (ListView):

![image](https://user-images.githubusercontent.com/7947027/194521611-bee81227-8313-4883-a647-e966b6480907.png)

Please be attentive and do the research in your own rather than expect for someone to fix your sloppy work
