### ISSUE TITLE
dataRowMinHeight / dataRowMaxHeight with fixed column got wrong value on row height

### ISSUE THREAD

**Issue by Chris2137** [maxim-saplin/data_table_2#191]
Thanks for updating data_table_2 to support the latest dataRowMinHeight and dataRowMaxHeight property in dataTable. 
My use case is that I wanted to apply the two properties in data_table_2, but then there is no corresponding constructor property available. I can workaround this using the DataTableTheme in context. But my use case make use of fixed column, where the fixed column row height is smaller than other non-fixed columns, then the result is the fixed column height is collapsed to a minimum height where the content is expanded to maximum height, causing the row contents are not aligning with the fixed column.

Would be great if it can be fixed, also to open up constructor property to provide the min max dataRowHeight.

Thank you.

**Comment by maxim-saplin** [comment]
Hi, could you please provide a simple code sample, e.g. you can you the /example folder and try reproduce the issue in one of the standard samples

**Comment by Chris2137** [comment]
You can easily see the effect of fixing more or less columns, then the height of the fixed column become the max height among fixed columns only (not including those non-fixed columns).

**Comment by maxim-saplin** [comment]
I see, thanks, will check what can be done

**Comment by maxim-saplin** [comment]
I'm afraid there's no good solution to the problem within the current architecture of the widget. Just like there's no variable width of columns (setting column width's to content size) for the reasons of complexity of syncing dimensions of fixed and scrollable rows, for the same reasons I would go with fixing row heights and ignoring min/max values.

**Comment by Chris2137** [comment]
Any chance that you could evaluate the row height by finding the maxRowHeight among all cell content within the same row, instead of just from the fixed column set?

**Comment by maxim-saplin** [comment]
In theory that is doable, in practice that's a solid overall of the entire widget structure and poor performance since it would require multiple layout passes - one of the most expensive operations in UI. At the very beginning of package creation I've chosen the tradeoff to not support Flutter's dynamic column width feature and implement sticky headers.. Apparently now that there're sticky columns the same tradeoff is required.

I'll be changing the widget to ignore the values on min/max height and lock row height to single value or have the explicitly overridden.

**Comment by Chris2137** [comment]
Well noted with thanks.

**Comment by maxim-saplin** [comment]
Published 2.5.2
