### ISSUE TITLE
Autosize dataRowHeight

### ISSUE THREAD

**Issue by YouSour** [maxim-saplin/data_table_2#2]
hi, i really like this package , everything is work fine , but i would like to set auto size for dataRowHeight , how can i do that ? this is also a problem everyone facing right now too , thank in advance :) [https://github.com/flutter/flutter/issues/70510](url)
![99134315-0b6d3b80-25d2-11eb-8c48-6d3644a7fc41 (1)](https://user-images.githubusercontent.com/9318106/116331214-75cd0d80-a7f9-11eb-9513-c1313b0ad782.png)

**Comment by maxim-saplin** [comment]
Indeed, all rows are fixed height and there're no overides for this parameter... Implementing auto height for Rows would require a separate pass for measuring the contents of cell which I decided to avoid for performance anf stability reasons (and that's why there's pseudo auto size for columns via S, M, L).

A quick feature to help with that kind of issue might be exposing the height of individual rows (and letting devs decide if they want certain rows size to differe from the default height).

Also I'd suggest making rows high enough to fit 3 lines right away:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/7947027/116354755-897c7200-a801-11eb-918f-0795d3facfdc.png">

Also I'd think of such workaropund as using Text.overflow to avoid the clips and communicate in a better way there's more text. I don't think the idea of different row height is the best looking option...

**Comment by YouSour** [comment]
@maxim-saplin hmm , i see , the reason i want it because my app allow user add more item to specific item that user selected , i don't want to use list view or singleChildScrollView to fix it , it look so bad for UI , do you have any tip or idea about it ?    

https://user-images.githubusercontent.com/9318106/116360444-205d2480-a82a-11eb-80a0-a4645008f59e.mov

**Comment by maxim-saplin** [comment]
I'd approach this kind of UI with a ListView or SliverScrollList with items/slivers having leftmost 3 columns fixed width (as well as checkbox column) and the Item column stretching to fill the remaining width. I don't think Table is the best widget for this task

**Comment by YouSour** [comment]
@maxim-saplin ok, can you suggest any package listView that come with checkbox and sticky header , same as dataTable ?

**Comment by maxim-saplin** [comment]
I don't think you need a separate widget for that, it's easilyy done with Columns, Rows and Flexible widgets - see example I've just put: https://dartpad.dev/bfa0246c49dd0b3cb9ad931b11eaa045?null_safety=true

You just need to update _Tile() widget to allow it accepting widgets instead of text and implement state and check-box slecetion logic - shouldn't be hard

**Comment by YouSour** [comment]
@maxim-saplin thank you, i will work on it :smile:
