### ISSUE TITLE
Column text title is shorted

### ISSUE THREAD

**Issue by fvisticot** [maxim-saplin/data_table_2#6]
With Flutter widget DataColumn, the title text is fully displayed.
With DataColumn2, the title is shorted 
Flutter lib:

![image](https://user-images.githubusercontent.com/153679/119557609-b0967700-bda0-11eb-9bfc-98dfdcdd477e.png)

data_table_2
![image](https://user-images.githubusercontent.com/153679/119557630-b5f3c180-bda0-11eb-8df3-03ed8b6fb417.png)

**Comment by maxim-saplin** [comment]
Hi. This is behaviour by design.

Flutter's DataTable takes whatever width is required to display it's columns - with unlimitted width it doesn't clip cells and can overflow its container.

DataTable2 is different in that regard since it always takes available width and stretches to fill the container. This width is then distributed among all columns. With too many columns or cells having large contents, cells get cliped.

For the above example I have 2 suggestions to avoid the clipping:

1. Set `minWidth` property on DataTable2 to some value that is enough to have cells not clipped - if the width of the container goes below the threshold, DataTable2 will show horizontal scroll bar.
2. Decrease **columnSpacing** and **horizontalMargin** properties. In the above example there's plenty white space which decrease the width available to cells for laying out their content.
