### ISSUE TITLE
How to hide loading indicator in AsyncPaginatedDataTable2?

### ISSUE THREAD

**Issue by felixalguzman** [maxim-saplin/data_table_2#79]
I have less data than the number of rows per page.

![image](https://user-images.githubusercontent.com/17243615/158677208-d62e7ab2-3fb3-4abf-91fa-9840ef4fa655.png)

**Comment by maxim-saplin** [comment]
Do you have those circles spinning all the time? Do you have a small reproduction repo that you can share for me to look at?

**Comment by ervindobri** [comment]
I think it's when the loaded data has a length < totalCount

**Comment by Amitpatil215** [comment]
This happens when, rowsPerPage is lets say 4
and actual rows returned is 2

This scenario usually comes at the last page, cause we might have total 10 records. on first two pages 4+4 =8 records are shown.
but on 3rd page we only have 2 rows to show, whereas it expects us to be returning 4 rows.  

Any workaround ? cc: @maxim-saplin
