### ISSUE TITLE
Remove highlight on row hover 

### ISSUE THREAD

**Issue by cedricDevWP** [maxim-saplin/data_table_2#80]
I didn't see the option to remove the highlight when hovering over a row : 

![Capture d’écran 2022-03-22 à 14 40 33](https://user-images.githubusercontent.com/12508260/159494773-a7e11d9e-a99f-4e4c-8cb3-6335fd01d2e7.png)

does this feature exist? or is there a way around this?

**Comment by maxim-saplin** [comment]
Hi @cedricDevWP, @nosmirck. You want to disable row color change when user hovers over a row? E.g. in the below screenshot the first row is grey cause there's a mouse pointer over it (not visible in the picture):

<img width="523" alt="image" src="https://user-images.githubusercontent.com/7947027/168532516-dc0e83fe-fcca-45c4-8fe5-29a285aa8791.png">

Do I get your question right?

**Comment by nosmirck** [comment]
@maxim-saplin yes, exactly. Specially because, at least in my case, we don't have any type of interaction with the table (no selection, tap, long tap, etc)

In my case, it's used to present the user a table that then they can print.

By Material Design, only interactive elements should have an inkwell, disabled buttons are usually grayed out to show the user that you can't interact with them, surfaces with inkwell are meant to be interactive. When we have the table with rows showing interactivity with the cursor but don't do anything that breaks the material design principles.

**Comment by maxim-saplin** [comment]
I see. Yet for me that is more of a feature rather than a bug. A reasonable exception from 'highlight interactive elements' rule - when going through wide tables highlighting a single row makes readability easier. Though it makes sense to have a param to disable that behaviour. I'd still keep the default behaviour with row being highlighted on hover.
